import { Check, Clock3, Copy, Download, ExternalLink, FileAudio, LoaderCircle } from "lucide-react";
import type { Stage, TranscriptChunk, TranscriptionResult } from "../../../entities/transcription";
import { backend } from "../../../shared/api";
import { Button } from "../../../shared/ui";

type Props = { result: TranscriptionResult | null; busy: boolean; copied: boolean; language: string; stage: Stage; streamLines: string[]; chunks: TranscriptChunk[]; onCopy: () => void };
const formatTime = (seconds?: number) => seconds ? `${Math.floor(seconds / 60)}분 ${Math.round(seconds % 60)}초` : "—";

export function TranscriptPanel({ result, busy, copied, language, stage, streamLines, chunks, onCopy }: Props) {
  return <aside className="animate-in delay-1"><div className="panel flex h-[520px] min-h-0 flex-col overflow-hidden">
    {result ? <><div className="flex shrink-0 items-center gap-3 border-b border-white/[.07] bg-white/[.018] px-5 py-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#d8ff65]/10 text-[#d8ff65]"><FileAudio size={18}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{result.title}</p><p className="mt-1 flex items-center gap-1.5 text-[11px] text-[#737a6e]"><Clock3 size={11}/>{formatTime(result.duration_seconds)} · {language === "auto" ? "자동 감지" : language.toUpperCase()}</p></div><CopyButton copied={copied} onCopy={onCopy}/></div><div className="transcript-scroll min-h-0 flex-1 overscroll-contain overflow-y-auto px-6 py-5"><p className="whitespace-pre-wrap text-[14px] leading-7 text-[#c5cabf]">{result.transcript}</p></div><div className="grid shrink-0 grid-cols-2 gap-2 border-t border-white/[.07] p-4"><Button variant="secondary" size="sm" onClick={() => backend.openArtifact(result.transcript_path)}><ExternalLink size={14}/>텍스트 열기</Button><Button variant="secondary" size="sm" onClick={() => backend.openArtifact(result.audio_path)}><Download size={14}/>오디오 열기</Button></div></> : busy ? <LiveStream lines={streamLines} chunks={chunks} stage={stage} copied={copied} onCopy={onCopy}/> : <EmptyState/>}
  </div></aside>;
}

function LiveStream({lines, chunks, stage, copied, onCopy}: {lines: string[]; chunks: TranscriptChunk[]; stage: Stage; copied: boolean; onCopy: () => void}) { const visible = lines.filter((line) => line.trim()).slice(-18); return <div className="flex min-h-0 flex-1 flex-col"><div className="flex shrink-0 items-center gap-2 border-b border-white/[.06] bg-[#d8ff65]/[.025] px-5 py-3 font-mono text-[10px] uppercase tracking-[.15em] text-[#9faa8f]"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#d8ff65]"/><span className="flex-1">Live transcript · {stage}</span><CopyButton copied={copied} disabled={chunks.length === 0} onCopy={onCopy}/></div><div className="transcript-scroll min-h-0 flex-1 overscroll-contain overflow-y-auto px-5 py-5">{chunks.length ? chunks.map((chunk, index) => <div key={`${index}-${chunk.timestamp}`} className="mb-4 animate-in"><span className="mb-1 block font-mono text-[9px] text-[#65705e]">{chunk.timestamp}</span><p className="text-[14px] leading-6 text-[#d4d9ce]">{chunk.text}</p></div>) : <div className="flex h-full items-center justify-center text-xs text-[#555c52]"><LoaderCircle size={14} className="mr-2 animate-spin"/>{stage === "transcribe" ? "첫 문장을 인식하는 중…" : "음성 인식을 준비하는 중…"}</div>}<div className="h-0" ref={(node) => node?.scrollIntoView({behavior: "smooth"})}/></div>{visible.length > 0 && <div className="shrink-0 truncate border-t border-white/[.06] bg-black/10 px-4 py-2 font-mono text-[9px] text-[#4f574c]">{visible[visible.length - 1]}</div>}</div> }
function CopyButton({copied, disabled, onCopy}: {copied: boolean; disabled?: boolean; onCopy: () => void}) { return <Button variant="secondary" size="sm" disabled={disabled} title="인식된 텍스트 전체 복사" onClick={onCopy}>{copied ? <><Check size={14} className="text-[#d8ff65]"/>복사됨</> : <><Copy size={14}/>전체 복사</>}</Button> }
function EmptyState() { return <div className="flex flex-1 flex-col items-center justify-center px-10 text-center"><div className="waveform mb-7 flex h-20 items-center gap-1">{Array.from({length: 22}).map((_, i) => <span key={i} style={{height: `${14 + ((i * 17) % 52)}px`, animationDelay: `${i * 45}ms`}} />)}</div><p className="font-display text-xl text-[#aeb4a8]">아직 조용하네요.</p><p className="mt-2 max-w-xs text-xs leading-5 text-[#5f665b]">변환을 시작하면 이곳에 영상 속 이야기가 차곡차곡 기록됩니다.</p></div> }
